services:
  postgres:
    image: postgres:latest
    container_name: inflearn-clone-db-test
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prismapass
      POSTGRES_DB: inflearn_clone-test
